# Uncomment the following to inject CLUSTER_TOKEN from a Secret
# apiVersion: v1
# kind: Secret
# metadata:
#   name: devzero-zxporter-cluster-secret
# type: Opaque
# stringData:
#   CLUSTER_TOKEN: "{{ .cluster_token }}"
