apiVersion: v1
kind: Secret
metadata:
  name: devzero-zxporter-token
type: Opaque
stringData:
  CLUSTER_TOKEN: "{{ .cluster_token }}"
  # Uncomment the following line to use PAT token instead of cluster token
  # If both are provided, CLUSTER_TOKEN takes precedence
  # PAT_TOKEN: "{{ .pat_token }}"
