apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
  namespace: system
data:
  # If using PAT token, you can comment out CLUSTER_TOKEN and use PAT_TOKEN in the Secret
  CLUSTER_TOKEN: "{{ .cluster_token }}"
  # PAT_TOKEN: "{{ .pat_token }}"  # Uncomment to use PAT token (recommended to use Secret instead)
  KUBE_CONTEXT_NAME: '{{ .kube_context_name }}'
  DAKR_URL: "https://dakr.devzero.io"
  PROMETHEUS_URL: "http://prometheus-dz-prometheus-server.devzero-zxporter.svc.cluster.local:80"
  K8S_PROVIDER: "{{ .k8s_provider }}"
  COLLECTION_FREQUENCY: ""
  BUFFER_SIZE: ""
  EXCLUDED_NAMESPACES: ""
  EXCLUDED_NODES: ""
  TARGET_NAMESPACES: ""
  DISABLE_NETWORK_IO_METRICS: ""
  MASK_SECRET_DATA: ""
  NODE_METRICS_INTERVAL: ""
  WATCHED_CRDS: ""
  DISABLED_COLLECTORS: ""
  EXCLUDED_PODS: ""
  EXCLUDED_DEPLOYMENTS: ""
  EXCLUDED_STATEFULSETS: ""
  EXCLUDED_DAEMONSETS: ""
  EXCLUDED_SERVICES: ""
  EXCLUDED_PVCS: ""
  EXCLUDED_EVENTS: ""
  EXCLUDED_JOBS: ""
  EXCLUDED_CRONJOBS: ""
  EXCLUDED_REPLICATIONCONTROLLERS: ""
  EXCLUDED_INGRESSES: ""
  EXCLUDED_INGRESSCLASSES: ""
  EXCLUDED_NETWORKPOLICIES: ""
  EXCLUDED_ENDPOINTS: ""
  EXCLUDED_SERVICEACCOUNTS: ""
  EXCLUDED_LIMITRANGES: ""
  EXCLUDED_RESOURCEQUOTAS: ""
  EXCLUDED_HPAS: ""
  EXCLUDED_VPAS: ""
  EXCLUDED_ROLES: ""
  EXCLUDED_ROLEBINDINGS: ""
  EXCLUDED_CLUSTERROLES: ""
  EXCLUDED_CLUSTERROLEBINDINGS: ""
  EXCLUDED_PDBS: ""
  EXCLUDED_PSPS: ""
  EXCLUDED_PVS: ""
  EXCLUDED_STORAGECLASSES: ""
  EXCLUDED_CRDS: ""
  EXCLUDED_CRDGROUPS: ""
  # Resource names for token storage (configurable for different environments)
  TOKEN_SECRET_NAME: "devzero-zxporter-token"
  TOKEN_CONFIGMAP_NAME: "env-config"
  USE_SECRET_FOR_TOKEN: "false"
