blank_issues_enabled: false
contact_links:
  - name: DevZero ZXporter Support
    url: https://www.devzero.io/support
    about: For questions or issues regarding DevZero ZXporter, please email [support@devzero.io](mailto:support@devzero.io) or visit our website.
  - name: Feature Requests and Enhancements
    url: https://www.devzero.io
    about: To suggest new features or enhancements for DevZero ZXporter, please submit a feature request using the appropriate template.
  - name: Documentation Feedback
    url: https://www.devzero.io/docs
    about: To report issues or suggest improvements to our documentation, please submit a documentation issue.
